# Generated by Django 4.2.1 on 2023-08-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_order_method_order_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
    ]
