# Generated by Django 4.2.1 on 2023-08-30 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_items_order_item_remove_order_ordered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='refund_granted',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_requested',
        ),
    ]
